spring:
  application:
    name: kidk-api
  profiles:
    active: default  # 기본 프로필
  datasource:
    url: jdbc:h2:file:./db/kidkdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true