name: KIDK Server Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 코드 가져오기
      - uses: actions/checkout@v4

      # 자바 21 세팅
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Firebase 키 파일 생성
      - name: Make Firebase Key File
        run: |
          # resources 폴더 없으면 만들기 
          mkdir -p ./src/main/resources
          # Secrets 에 저장된 내용을 파일로 쓰기 
          echo "${{ secrets.FIREBASE_KEY }}" > ./src/main/resources/firebase-service-account.json

      # Gradle 빌드
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      # 빌드된 파일(jar)을 EC2 서버로 전송 (SCP)
      - name: Send Jar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "./build/libs/*.jar"
          target: "/home/${{ secrets.EC2_USERNAME }}/kidk-server"

      # 서버 접속해서 재시작 (SSH)
      - name: Deploy & Restart
        uses: appleboy/ssh-action@master
        with:

          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 서버 정보 확인 
            cat /etc/os-release
            
            # 현재 실행 중인 자바 서버 종료 (없으면 패스)
            sudo fuser -k 8080/tcp || true
            
            # 새 서버 시작 
            # 환경변수로 주입
            JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            DB_URL="${{ secrets.DB_URL }}" \
            DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            S3_ACCESS_KEY="${{ secrets.S3_ACCESS_KEY }}" \
            
            S3_SECRET_KEY="${{ secrets.S3_SECRET_KEY }}" \

            # 추후 HTTPS 설정 
            REQUIRE_HTTPS="false" \
            nohup java -jar \
            -DDB_DRIVER="com.mysql.cj.jdbc.Driver" \
            $(find /home/${{ secrets.EC2_USERNAME }}/kidk-server/build/libs -name "*.jar" ! -name "*plain.jar" | head -n 1) >> ./app.log 2>&1 &